import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "SignUp Tremor Dashboard",
  description: "Tremor Dashboard generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="icon" href="/assets/images/favicon.ico" />
      <body>{children}</body>
    </html>
  );
}
