"use client";

import { useContext } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

// Styles
import "./globals.css";

// Contexts
import { ThemeContext } from "@/context/theme";

interface ClientRootLayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Tremor Dashboard",
  description: "Tremor Dashboard generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

const ClientRootLayout = ({ children }: ClientRootLayoutProps) => {
  const { theme } = useContext(ThemeContext);

  return (
    <div className={`${inter.className} ${theme ? "dark" : "light"}`}>
      {children}
    </div>
  );
};

export default ClientRootLayout;
