"use client";

import { useContext } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

// Styles
import "./globals.css";

// Contexts
import { ThemeContext } from "@/context/theme";

interface ClientRootLayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Tremor Dashboard",
  description: "Tremor Dashboard generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

const ClientRootLayout = ({ children }: ClientRootLayoutProps) => {
  const { isDarkTheme } = useContext(ThemeContext);

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/assets/images/favicon.ico" />
      </head>
      {/* TODO: Add class to custom theme dark or light */}
      <body className={`${inter.className} ${isDarkTheme ? "dark" : "light"}`}>
        {children}
      </body>
    </html>
  );
};

export default ClientRootLayout;
