// Libs
import type { Metadata } from "next";

// Styles
import "./globals.css";

// Context
import { ThemeProvider } from "@/context/theme";

// Components
import ClientRootLayout from "./ClientRootLayout";

export const metadata: Metadata = {
  title: "Tremor Dashboard",
  description: "Tremor Dashboard generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider>
      <ClientRootLayout>{children}</ClientRootLayout>
    </ThemeProvider>
  );
}
